var dataMockup = [
  [
    {
      Title: "Van Ban Chinh",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      IsMainDoc: true,
      DocumentId: 27737,
      DocumentTypeId: 2,
      RelateType: 2,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ1",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 8,
      RelateType: 8,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ1.1",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 8,
      RelateType: 2,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ1.1.1",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 8,
      RelateType: 2,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ2",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 8,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ3",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 8,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ4",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 8,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ5",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 16,
      RelateType: 8,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ6",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 16,
      RelateType: 8,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ7",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 16,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ7.7.1",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 16,
      RelateType: 4,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ8",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 4,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ9",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 4,
      RelateType: 8,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ10",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 4,
      RelateType: 8,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ11",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 4,
      RelateType: 2,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ12",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 2,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ12.1",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 2,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ12.2",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 2,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ12.3",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 2,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ12.4",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 2,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ13",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 2,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ14",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 2,
      RelateType: 16,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
    {
      Title: "Van Ban LQ15",
      StorageCode: "Uyen CL 20009",
      Url: "/vi/van-ban-chat-luong/chinh-sach-2/van-ban-chinhdocx-27736.html",
      Description: null,
      Version: 100,
      Code: "Uyen CL 20009",
      Status: 1,
      DocumentId: 27737,
      DocumentTypeId: 2,
      RelateType: 8,
      IssueDepartmentId: 11725,
      IsHide: null,
      SecurityLevel: 1,
      IssueDate: "2020-09-20T00:00:00",
      LanguageId: 1066,
      RelationTypeString: "Văn bản bị sửa đổi bổ sung",
      SectionId: null,
      ID: 2551,
      StatusName: "Đang hiệu lực",
      TableName: "DocumentRelate",
      LangDocumentId: null,
      UrlEN: "",
    },
  ],
  [
    {
      ID: 43,
      RelateTypeId: 2,
      Color: "#ff0000",
      DirectionArrow: 1,
      Created: "2020-10-23T14:01:04.26",
      Modified: "2020-10-23T16:47:29.433",
      Status: 1,
      Zone: 1,
      Rank: 1,
    },
    {
      ID: 47,
      RelateTypeId: 4,
      Color: "#00f379",
      DirectionArrow: 1,
      Created: "2020-10-23T14:07:03.26",
      Modified: "2020-10-23T16:47:26.98",
      Status: 1,
      Zone: 2,
      Rank: 55,
    },
    {
      ID: 48,
      RelateTypeId: 8,
      Color: "#00ff00",
      DirectionArrow: 2,
      Created: "2020-10-23T16:30:44.487",
      Modified: "2020-10-23T16:47:24.04",
      Status: 1,
      Zone: 3,
      Rank: 3,
    },
    {
      ID: 48,
      RelateTypeId: 16,
      Color: "#f01fff",
      DirectionArrow: 2,
      Created: "2020-10-23T16:30:44.487",
      Modified: "2020-10-23T16:47:24.04",
      Status: 1,
      Zone: 4,
      Rank: 3,
    },
  ],
  [
    {
      ID: 41,
      DocumentTypeId: 2,
      Color: "#80f711",
      Rank: 2,
      Created: "2020-10-23T15:39:17.827",
      Modified: "2020-10-26T13:42:44.103",
      Status: 1,
    },
    {
      ID: 39,
      DocumentTypeId: 4,
      Color: "#ffe600",
      Rank: 1,
      Created: "2020-10-23T14:00:05.613",
      Modified: "2020-10-26T13:42:56.173",
      Status: 1,
    },
    {
      ID: 38,
      DocumentTypeId: 8,
      Color: "#f200ff",
      Rank: 3,
      Created: "2020-10-23T13:59:44.483",
      Modified: "2020-10-26T13:43:01.047",
      Status: 1,
    },
    {
      ID: 42,
      DocumentTypeId: 16,
      Color: "#00aeff",
      Rank: 3,
      Created: "2020-10-23T15:55:15.63",
      Modified: "2020-10-26T13:43:39.557",
      Status: 4,
    },
  ],
];
